baseURL = "https://orlando-nest-blog.pages.dev/"
languageCode = "en-us"
title = "Orlando Nest Blog"
theme = "tella"
paginate = 10

[params]
  author = "Ted Moseley"
  description = "Real estate blog covering Orlando & Central Florida lifestyle, home buying & selling tips, market trends, and community spotlights."
  # enableDarkMode = true
  favicon = "favicon-32x32.png"

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  blog = "/blog/:slug/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[menu]

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 4
