baseURL = "https://orlando-nest-blog.pages.dev/"
languageCode = "en-us"
title = "Orlando Nest Blog"
theme = "tella"

[params]
  description = "Your trusted source for real estate tips, insights, and updates across Orlando and Central Florida."
  author = "Ted Moseley – Orlando Nest"
  
  [params.logo]
    main = "images/WebsiteIcon.png"
    alt = "Orlando Nest logo"
    size = "h-10 w-auto"

[menu]
    
      [[menu.main]]
        name = "Blog"
        url = "/"
        weight = 1
    
      [[menu.main]]
        name = "About"
        url = "https://orlandonest.com/about"
        weight = 2
    
      [[menu.main]]
        name = "Contact"
        url = "https://orlandonest.com/contact"
        weight = 3
    

[outputs]
home = ["HTML", "RSS"]

[params]
mainSections = ["blog"]
